GET http://localhost:8080/users

###
POST http://localhost:8080/users

###
GET http://localhost:8080/posts

###
POST http://localhost:8080/posts

###
GET http://localhost:8080/comments

###
POST http://localhost:8080/comments