spring:
  datasource:
    # PostgreSQL
    url: jdbc:postgresql://localhost:37113/demo
    username: root
    password: 123456
  jpa:
    hibernate:
      # create and drop table, good for testing, production set to none or comment it
      ddl-auto: create-drop

conf:
  protocol: "https"
  jsonplaceholder:
    host: "jsonplaceholder.typicode.com"
    endpoints:
      users: "/users"
      posts: "/posts"
      comments: "/comments"