  name: build and deploy spring exercise
  on:
    push:
      branches:
        - main

  defaults:
    run:
      working-directory: ./test-calculator

  jobs:
    build-deploy:
      name: build and deploy spring-api
      runs-on: ubuntu-24.04
      defaults:
        run:
          working-directory: ./test-calculator
      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setup jdk 21
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 21

        - name: bash
          run: pwd && ls
          
        # - name: unit tests
        #   run: mvn -B test --file pom.xml

        - name: build the app
          run: |
            mvn clean
            mvn -B package --file pom.xml

        - name: login to docker hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_PASSWORD }}

        - name: push the docker image to docker hub
          uses: docker/build-push-action@v4
          with:
            context: ./test-calculator
            file: ./test-calculator/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_NAME }}/test-calculator:latest
